name: 'GitHub Actions for Upbound - up'
description: 'Connect to Upbound using up CLI'
author: 'upbound'

# Define your inputs here.
inputs:
  channel:
    description: 'Installation channel for up'
    default: 'stable'
  version:
    description: 'Version of up to install'
    default: 'current'
  url:
    description: 'Where to download up from'
    default: 'https://cli.upbound.io'
  api-token:
    description: 'Upbound API token'
    default: ''
  skip-login:
    description: 'Skip login'
    default: 'false'

runs:
  using: node20
  main: dist/index.js
