name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install up
        id: test-action
        uses: ./
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: github-actions-test

      - name: Verify Installation
        run: up version

  test-action-skip-login:
    name: GitHub Actions Test skip-login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install up
        id: test-action
        uses: ./
        with:
          skip-login: true

      - name: Verify Installation
        run: up version

  test-action-skip-login-custom-version:
    name: GitHub Actions Test custom version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install up
        id: test-action
        uses: ./
        with:
          version: v0.32.0
          skip-login: true

      - name: Verify Installation
        run: |
          INSTALLED_VERSION=$(up version --client | yq .Client.Version)
          if [[ "$INSTALLED_VERSION" != "v0.32.0 "]]; then
            echo "Error: Expected version v0.32.0 but got $INSTALLED_VERSION"
            exit 1
          fi
